name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   # - name: configure
   #   run: ./configure
    - name: make
      run: make

   # - name: size
     # run:  arm-none-eabi-size k5prog

   # - name: rename
    #  run: mv k5prog.exe k5prog${{ github.event.release.tag_name }}.exe

    - name: Get the date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    #- name: 'Add unpacked k5prog to release'
    #  uses: svenstaro/upload-release-action@v2
      #with:
       # file: k5prog.exe
     #   asset_name: ${{ format('k5prog.raw_{0}.exe', github.run_number) }}
     #   tag: ${{ format('release-{0}', github.run_number) }}
   #     release_name: ${{ format('Release {0}, {1}', github.run_number, steps.date.outputs.date) }}
  
    - name: 'Add k5prog to release'
      uses: svenstaro/upload-release-action@v2
      with:
        file: k5prog${{ github.event.release.tag_name }}.exe
        asset_name: ${{ format('k5prog_v{0}.exe', github.run_number) }}
        tag: ${{ format('release-{0}', github.run_number) }}
        release_name: ${{ format('Release {0}, {1}', github.run_number, steps.date.outputs.date) }}
#created_at
