name: 'release'
on:
  push:
#name: C/C++ CI

#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   # - name: configure
   #   run: ./configure
    - name: make
      run: make
   # - name: make check
   #   run: make check
   # - name: make distcheck
   #   run: make distcheck
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: k5prog.exe
        path: k5prog
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: k5prog.exe
        artifacts: k5prog.exe
        tag: v1.1.1
